service: demo-glue-crawler  # an alias for the stack

useDotenv: true  # Enables creating env variables


provider:
  name: aws
  region: us-east-2

  stackTags:                 # helps in tracking and monitoring costs etc
    product: datateam
    env: qa
    created-date: 2023-07-25
    team: data
    customer-impact: false
    terraform: false

resources:
  Resources:
    testGlueDatabase:
      Type: AWS::Glue::Database
      Properties:
        CatalogId: ${env:ACCOUNT}   # here it is aws account id
        DatabaseInput:
          Name: ${env:DB_NAME}

    TableGlueCrawler: 
      Type: AWS::Glue::Crawler
      Properties:
        DatabaseName: ${env:DB_NAME}
        Name: ${env:CRAWLER_NAME}
        RecrawlPolicy:
          RecrawlBehavior: CRAWL_EVERYTHING
        Role: ${env:GLUE_ROLE_ARN}
        SchemaChangePolicy:
          DeleteBehavior: DEPRECATE_IN_DATABASE
        Targets:
          S3Targets:
            - Path: ${env:CRAWLER_TARGET_PATH}